---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: zcon-srchoi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: ghcr.io/zcon-srchoi/tta_devops/my-app:latest  # GHCR 이미지 경로
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: ghcr-secret  # 생성한 ImagePullSecret 참조

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: zcon-srchoi
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30173  # NodePort 직접 지정 (예시)
  type: NodePort
